// ==================================================================
//  GOLF_MemberLocker
// ==================================================================
association GOLF_MemberLocker : GOLF_Base {
       [Max(1)]
    GOLF_ClubMember REF Member;
    GOLF_Locker REF Locker;
    GOLF_Date AssignedOnDate;
};