name: .NET

on:

  push:
    branches:
      - master
      - 'feature/*'

  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: dotnet restore
      run: dotnet restore src/Kingsland.MofParser.sln

    - name: dotnet build
      run: dotnet build src/Kingsland.MofParser.sln --configuration Release --no-restore

    - name: dotnet test
      run: dotnet test src/Kingsland.MofParser.sln --configuration Release --no-build --verbosity normal

    - name: nuget pack
      run: nuget pack src/Kingsland.MofParser.nuspec
